version: '3'
services:
  tomcat:
    restart: always
    build: ./tomcat
    ports:
     - "80:8080"
    volumes:
     - ./code:/code
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
     - "8090:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  code: