version: '3'
services:
  tomcat:
    restart: always
    build: ./tomcat
    command: catalina.sh jpda run
    environment:
        JPDA_ADDRESS: 8000
    ports:
     - "80:8080"
     - "8000:8000"
    volumes:
     - ./code:/code
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mariadb-volume:/var/lib/mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
     - "8090:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  code:
  mariadb-volume: