version: '3'
services:
  tomcat:
    restart: always
    build: ./tomcat
    command: catalina.sh jpda run
    ports:
     - "80:8080"
    volumes:
     - ./code:/code
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mariadb-volume:/var/lib/mysql

volumes:
  code:
  mariadb-volume: